# Generated by Django 6.0.8 on 2026-09-19 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('change_seq', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'synchronization state',
            },
        ),
        migrations.CreateModel(
            name='ProcessedMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutation_id', models.UUIDField(editable=False, unique=True)),
                ('client_id', models.UUIDField()),
                ('sequence', models.BigIntegerField(blank=True, null=True)),
                ('client_created_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('rejected', 'Rejected')], max_length=16)),
                ('code', models.CharField(max_length=64)),
                ('detail', models.TextField()),
                ('change_seq', models.BigIntegerField(blank=True, null=True)),
                ('envelope', models.TextField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'processed mutation',
                'ordering': ['-processed_at', '-id'],
                'indexes': [models.Index(fields=['user', 'processed_at'], name='sync_mutation_user_time')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['applied', 'rejected'])), name='sync_mutation_status_valid')],
            },
        ),
    ]
