# Generated by Django 6.0.8 on 2026-09-19 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processedmutation',
            name='envelope_truncated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='processedmutation',
            index=models.Index(fields=['user', 'client_id', 'sequence'], name='sync_mutation_device_seq'),
        ),
    ]
