# Generated by Django 6.0.8 on 2026-09-19 11:20

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PadDefaults',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('speed_kmh', models.DecimalField(decimal_places=2, default=Decimal('5.0'), help_text='Treadmill speed in km/h.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('incline_pct', models.DecimalField(decimal_places=2, default=Decimal('2.0'), help_text='Treadmill incline in percent.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_bout_seconds', models.PositiveIntegerField(default=480, help_text='Maximum bout duration in seconds (480 = 8 minutes).', validators=[django.core.validators.MinValueValidator(1)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PAD defaults',
                'verbose_name_plural': 'PAD defaults',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='pad_defaults_singleton'), models.CheckConstraint(condition=models.Q(('speed_kmh__gt', 0)), name='pad_defaults_speed_positive'), models.CheckConstraint(condition=models.Q(('incline_pct__gte', 0)), name='pad_defaults_incline_non_negative'), models.CheckConstraint(condition=models.Q(('max_bout_seconds__gte', 1)), name='pad_defaults_max_bout_positive')],
            },
        ),
        migrations.CreateModel(
            name='WalkingSession',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_client_id', models.UUIDField(editable=False)),
                ('last_sequence', models.BigIntegerField(editable=False)),
                ('change_seq', models.BigIntegerField(editable=False)),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DISCARDED', 'Discarded')], max_length=16)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('speed_kmh', models.FloatField()),
                ('incline_pct', models.FloatField()),
                ('max_bout_seconds', models.PositiveBigIntegerField()),
                ('session_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalkingBout',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_client_id', models.UUIDField(editable=False)),
                ('last_sequence', models.BigIntegerField(editable=False)),
                ('change_seq', models.BigIntegerField(editable=False)),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True)),
                ('bout_number', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('pain_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pain_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, choices=[('MAX_DURATION', 'Maximum duration'), ('CLAUDICATION', 'Claudication'), ('FOOT_NUMBNESS', 'Foot numbness'), ('SUDDEN_SWELLING', 'Sudden swelling'), ('OTHER', 'Other')], max_length=32, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('walking_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouts', to='pad.walkingsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalkingBoutPause',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_client_id', models.UUIDField(editable=False)),
                ('last_sequence', models.BigIntegerField(editable=False)),
                ('change_seq', models.BigIntegerField(editable=False)),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('walking_bout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='pad.walkingbout')),
            ],
            options={
                'verbose_name': 'walking bout pause',
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'change_seq'], name='pad_walkingboutpause_feed')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='pad_pause_ended_after_start'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('ended_at__isnull', True)), fields=('walking_bout',), name='pad_one_open_pause_per_bout')],
            },
        ),
        migrations.CreateModel(
            name='WalkingRest',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_client_id', models.UUIDField(editable=False)),
                ('last_sequence', models.BigIntegerField(editable=False)),
                ('change_seq', models.BigIntegerField(editable=False)),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('walking_bout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rests', to='pad.walkingbout')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'change_seq'], name='pad_walkingrest_feed')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='pad_rest_ended_after_start'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('walking_bout',), name='pad_one_rest_per_bout')],
            },
        ),
        migrations.AddIndex(
            model_name='walkingsession',
            index=models.Index(fields=['user', 'change_seq'], name='pad_walkingsession_feed'),
        ),
        migrations.AddConstraint(
            model_name='walkingsession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'COMPLETED', 'DISCARDED'])), name='pad_session_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='walkingsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'ACTIVE')), models.Q(('completed_at__isnull', False), ('status__in', ['COMPLETED', 'DISCARDED'])), _connector='OR'), name='pad_session_completion_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='walkingsession',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='pad_session_completed_after_start'),
        ),
        migrations.AddConstraint(
            model_name='walkingsession',
            constraint=models.CheckConstraint(condition=models.Q(('speed_kmh__gt', 0)), name='pad_session_speed_positive'),
        ),
        migrations.AddConstraint(
            model_name='walkingsession',
            constraint=models.CheckConstraint(condition=models.Q(('incline_pct__gte', 0)), name='pad_session_incline_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='walkingsession',
            constraint=models.CheckConstraint(condition=models.Q(('max_bout_seconds__gte', 1)), name='pad_session_max_bout_positive'),
        ),
        migrations.AddConstraint(
            model_name='walkingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'ACTIVE')), fields=('user',), name='pad_one_active_session_per_user'),
        ),
        migrations.AddIndex(
            model_name='walkingbout',
            index=models.Index(fields=['user', 'change_seq'], name='pad_walkingbout_feed'),
        ),
        migrations.AddConstraint(
            model_name='walkingbout',
            constraint=models.CheckConstraint(condition=models.Q(('bout_number__gte', 1)), name='pad_bout_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='walkingbout',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='pad_bout_ended_after_start'),
        ),
        migrations.AddConstraint(
            model_name='walkingbout',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pain_max__isnull', True), ('pain_min__isnull', True)), models.Q(('pain_max__isnull', False), ('pain_max__lte', 5), ('pain_min__gte', 1), ('pain_min__isnull', False), ('pain_min__lte', models.F('pain_max')), ('pain_max__lte', django.db.models.expressions.CombinedExpression(models.F('pain_min'), '+', models.Value(1)))), _connector='OR'), name='pad_bout_pain_valid'),
        ),
        migrations.AddConstraint(
            model_name='walkingbout',
            constraint=models.CheckConstraint(condition=models.Q(('stop_reason__isnull', True), ('stop_reason__in', ['MAX_DURATION', 'CLAUDICATION', 'FOOT_NUMBNESS', 'SUDDEN_SWELLING', 'OTHER']), _connector='OR'), name='pad_bout_stop_reason_valid'),
        ),
        migrations.AddConstraint(
            model_name='walkingbout',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('ended_at__isnull', True)), fields=('walking_session',), name='pad_one_open_bout_per_session'),
        ),
    ]
