# Generated by Django 6.0.8 on 2026-09-21 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='walkingbout',
            name='pain_onset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='walkingbout',
            constraint=models.CheckConstraint(condition=models.Q(('pain_onset_at__isnull', True), models.Q(('pain_onset_at__gte', models.F('started_at')), models.Q(('ended_at__isnull', True), ('pain_onset_at__lte', models.F('ended_at')), _connector='OR')), _connector='OR'), name='pad_bout_pain_onset_within_bout'),
        ),
    ]
